runtime: nodejs20

env: standard

instance_class: F1

automatic_scaling:
  min_instances: 0
  max_instances: 1

env_variables:
  NODE_ENV: production
  PORT: 8080
  JWT_SECRET: visitor-management-secret-key-2024
  GCS_BUCKET_NAME: carbon-theorem-474515-b2.appspot.com

